title: ML Reading Group
description: Weekly agenda, resources, and slides for the ML/RL Reading Group at the Center for Distributed and Grid Computing
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
